export const QUESTION_EXPLANATIONS: Record<string, string> = {
    "q-001": "<p>The United States operates as a <strong>republic</strong> or a <strong>representative democracy</strong>. This means that instead of citizens voting directly on every law, they elect representatives at the local, state, and federal levels to govern on their behalf.</p><p>This system of government prevents placing too much power in the hands of one person or a small group, adhering to the principles of a constitution-based federal republic.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the Founding Fathers were drafting the U.S. Constitution, they were inspired by ancient Rome's republic and even debated whether to have a monarchy? They ultimately chose a system to ensure that power rests with the people, leading to the democratic government we have today!</p></div>",

    "q-002": "<p>The <strong>U.S. Constitution</strong> is the supreme law of the land. Established in 1787, it overrules any state laws or local ordinances that contradict it.</p><p>This ensures that the country follows a unified legal framework and guarantees that no group or state can undermine the fundamental laws of the United States.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the U.S. Constitution was signed on September 17, 1787, during a hot summer in Philadelphia, and many delegates were so eager to keep their discussions secret that they closed the windows to prevent eavesdropping? This secretive vibe helped create the foundational law that unites all Americans!</p></div>",

    "q-003": "<p>The U.S. Constitution creates the structure of the government and defines its powers. More importantly, it acts as a shield that <strong>protects the basic rights of the people</strong> from federal overreach.</p><p>By establishing a separation of powers and including the Bill of Rights, it ensures a balanced and fair system of governance.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the U.S. Constitution was signed in 1787 during a hot summer in Philadelphia, where delegates had to keep the windows shut to avoid being overheard? This secretive atmosphere led to a document that not only set up the government but also fiercely protected individual rights!</p></div>",

    "q-004": "<p>The famous phrase <strong>\"We the People\"</strong> embodies the idea of <em>self-government</em>. It signifies that the power to govern comes directly from the citizens, not from a king or an elite ruling class.</p><p>This reflects the concept of \"popular sovereignty,\" meaning the government exists only by the consent of the governed.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the phrase \"We the People\" was a bold departure from the past, as it replaced the traditional notion of rule by kings? This revolutionary idea made the U.S. Constitution one of the first documents to declare that the government is truly of, by, and for the people!</p></div>",

    "q-005": "<p>Changes to the U.S. Constitution are called <strong>amendments</strong>. The amendment process is intentionally difficult to prevent frivolous changes to the nation's foundational laws.</p><p>An amendment must be proposed by a two-thirds majority in Congress and then ratified by three-fourths of the states.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the U.S. Constitution has been amended 27 times since it was ratified in 1788, and the first ten amendments, known as the Bill of Rights, were added just a few years later in 1791 to safeguard individual liberties?</p></div>",

    "q-006": "<p>The <strong>Bill of Rights</strong> is the first ten amendments to the U.S. Constitution. It protects the <strong>basic rights and fundamental liberties</strong> of everyone living in the United States.</p><p>These include freedom of speech, freedom of religion, and the right to a fair trial, ensuring the government cannot take these freedoms away.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Bill of Rights was initially met with skepticism? Many founders, like Alexander Hamilton, thought it was unnecessary, believing that the Constitution already limited government powers—yet it was the promise of these rights that helped ratify the Constitution and protect individual freedoms!</p></div>",

    "q-007": "<p>The U.S. Constitution currently has <strong>27 amendments</strong>. Since it was ratified over two centuries ago, it has only been changed 27 times, showing how robust the original document was.</p><p>The first ten make up the Bill of Rights, while later ones abolished slavery, granted women the right to vote, and lowered the voting age to 18.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know the U.S. Constitution was ratified in 1788 but didn't get its first ten amendments, known as the Bill of Rights, until 1791? That's like waiting three years for the essential toppings on your favorite pizza!</p></div>",

    "q-008": "<p>The <strong>Declaration of Independence</strong>, adopted on July 4, 1776, is important because it officially announced that the 13 American colonies were breaking away from British rule.</p><p>It also stated the revolutionary idea that \"all men are created equal\" and possess unalienable rights: Life, Liberty, and the pursuit of Happiness.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Declaration of Independence was actually written on a desk that belonged to Thomas Jefferson's mother? This desk, called a \"writing slope,\" became a symbol of freedom as Jefferson penned the ideas that sparked a revolution and changed the course of history!</p></div>",

    "q-009": "<p>The <strong>Declaration of Independence</strong> is the founding document that declared the American colonies free from British control.</p><p>By signing this document, the Founding Fathers committed treason against the British Crown, sparking the American Revolutionary War in pursuit of a new, independent nation.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the Declaration of Independence was adopted on July 4, 1776, it was such a bold act that some signers were so nervous they had to hide from British soldiers? Talk about putting your signature on the line for freedom!</p></div>",

    "q-010": "<p>Two highly fundamental ideas from America's founding documents are <strong>equality</strong> and <strong>liberty</strong>.</p><p>These principles insist that all people are created equal with inherent natural rights, and that government must be limited so as not to infringe upon people's freedoms.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Thomas Jefferson, the principal author of the Declaration of Independence, famously borrowed ideas from Enlightenment thinkers like John Locke, who argued that life, liberty, and property are natural rights? This blend of philosophy and rebellion helped ignite the spark for American democracy!</p></div>",

    "q-011": "<p>These iconic words are found in the <strong>Declaration of Independence</strong>. They represent the core philosophy of the American identity: that every individual has the right to live freely and pursue their own personal goals and dreams without oppressive government interference.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Thomas Jefferson, the principal author of the Declaration of Independence, originally included \"property\" instead of \"pursuit of Happiness,\" but he believed the latter captured the American spirit of self-determination and aspiration even better, reflecting the revolutionary idea that happiness is a right worth fighting for!</p></div>",

    "q-012": "<p>The economic system of the United States is <strong>capitalism</strong>, also known as a <strong>free market economy</strong>.</p><p>In this system, private individuals and businesses own property, create goods, and determine prices based on supply and demand, rather than the government directing the economy.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">In the late 1700s, with the birth of the United States, many Founding Fathers envisioned a nation where individuals could thrive in a free market, leading to the iconic American Dream—where even a humble apple seller could become a millionaire!</p></div>",

    "q-013": "<p>The <strong>rule of law</strong> is the principle that <em>everyone</em>, from ordinary citizens to the President and government leaders, must obey the law.</p><p>It means that no one is above the law, and the legal system must be applied fairly protecting the country against dictatorship and corruption.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">In 1215, King John of England was forced to sign the Magna Carta, a groundbreaking document that established the idea that even the king was subject to the law—an early step in the journey towards the rule of law that we cherish today!</p></div>",

    "q-014": "<p>The U.S. Constitution was influenced by several major historical documents. A famous example is the <strong>Declaration of Independence</strong>.</p><p>Other key influences include the <em>Magna Carta</em>, the <em>Mayflower Compact</em>, and the <em>Federalist Papers</em>, all of which debated the balance of power and liberty.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Declaration of Independence was actually a bold breakup letter? Written in 1776, it announced America's split from British rule and laid the groundwork for the values of freedom and democracy that would later shape the U.S. Constitution!</p></div>",

    "q-015": "<p>The government is divided into three separate branches to maintain a system of <strong>checks and balances</strong> (or separation of powers).</p><p>The Founders designed this intentionally so that no single person or branch could become too powerful and rule like a tyrant or king.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the Founding Fathers crafted the U.S. Constitution, they were inspired by the ancient Roman Republic, where power was shared among the Senate, consuls, and assemblies—ensuring that no single ruler could dominate, much like how today’s branches keep each other in check!</p></div>",

    "q-016": "<p>The three branches of the U.S. government are the <strong>Legislative</strong>, <strong>Executive</strong>, and <strong>Judicial</strong> branches.</p><p>Congress makes the laws (Legislative), the President enforces the laws (Executive), and the Supreme Court interprets the laws (Judicial).</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the idea of separating government powers into three branches was inspired by ancient Rome and the Enlightenment thinker Montesquieu? This clever setup ensures that no single branch gets too powerful, just like a well-balanced three-legged stool!</p></div>",

    "q-017": "<p>The President of the United States is the head of the <strong>Executive Branch</strong>.</p><p>The primary role of the Executive Branch is to carry out and enforce the federal laws passed by Congress, as well as to direct foreign policy and command the armed forces.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that George Washington, the first President, set the precedent for the Executive Branch by refusing to serve more than two terms? This established a tradition that kept the presidency from becoming a monarchy, emphasizing the importance of checks and balances in our government!</p></div>",

    "q-018": "<p><strong>Congress</strong> (or the Legislative Branch) is the part of the federal government that writes and passes laws.</p><p>It is designed to be the branch closest to the people, ensuring that laws represent the will of the citizens.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the U.S. Congress has the power to create laws that can even override a presidential veto? This means that if Congress can gather a two-thirds majority in both chambers, they can still make a law against the President's wishes—talk about checks and balances in action!</p></div>",

    "q-019": "<p>The U.S. Congress is a bicameral (two-chamber) legislature consisting of the <strong>Senate</strong> and the <strong>House of Representatives</strong>.</p><p>This structure was a compromise during the Constitutional Convention to balance the power between large and small states.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">During the Constitutional Convention of 1787, delegates famously debated whether to give more power to large or small states, leading to the creation of the Senate—where each state has two votes—and the House of Representatives, where representation is based on population, balancing the scales like a political seesaw!</p></div>",

    "q-020": "<p>One major power of the U.S. Congress is the ability to <strong>write laws</strong>. It also holds the sole power to <strong>declare war</strong>.</p><p>Additionally, Congress controls the federal budget (collecting taxes and deciding how money is spent) and regulates interstate and foreign commerce.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that in 1812, the U.S. Congress declared war on Britain without a formal declaration of war in the traditional sense? This led to the War of 1812, proving that Congress's power to declare war has been a pivotal aspect of American history since the nation’s early days!</p></div>",

    "q-021": "<p>There are <strong>100 U.S. Senators</strong>. Because each of the 50 states is given exactly two senators, the total number always equals the number of states times two.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the U.S. Senate was created in 1789, it was designed to balance the power of populous states with smaller ones? This clever setup means every state, regardless of size, gets two senators, making a grand total of 100!</p></div>",

    "q-022": "<p>A U.S. Senator is elected to serve a term of <strong>six years</strong>.</p><p>These longer terms allow Senators to focus on long-term national policies and be somewhat insulated from the constant pressures of campaigning.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the U.S. Constitution was ratified in 1788, senators originally served terms of just six years, but they had to be at least 30 years old and a resident of the state they represented? This age requirement was designed to ensure that senators brought experience and wisdom to the legislative table!</p></div>",

    "q-023": "<p>The answer to this question <strong>varies depending on which state you currently live in</strong>. Each state has two U.S. Senators who represent all the citizens of that state in Congress. You can look up your state's current senators online.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the U.S. Senate was first established in 1789, each state only had one senator? It wasn't until later that the Founding Fathers decided that every state would send two senators to represent their interests in Congress, creating a stronger voice for each state's citizens!</p></div>",

    "q-024": "<p>There are <strong>435 voting members</strong> in the House of Representatives. This number has been permanently set by a law passed in 1929.</p><p>These 435 seats are divided among the 50 states proportionally based on each state's total population.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the number 435 was chosen to balance representation and manageability? Before the 1929 law, the House had grown so large it was like a wild game of musical chairs—too many members and no room to sit!</p></div>",

    "q-025": "<p>A member of the House of Representatives serves a term of <strong>two years</strong>.</p><p>Because they face reelection so frequently, they are forced to stay highly attuned and responsive to the immediate needs and opinions of the voters in their local district.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">In 1789, when the House of Representatives was established, the Founding Fathers believed a two-year term would keep representatives closely connected to their constituents, ensuring that even the most pressing local issues wouldn't go unaddressed—like a political sprint every two years to stay in touch with voters!</p></div>",

    "q-026": "<p>U.S. representatives serve shorter, 2-year terms so that they <strong>closely follow public opinion</strong>.</p><p>By standing for election frequently, they are constantly held accountable and represent the most current needs and attitudes of their local communities.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Founding Fathers designed the House of Representatives to be like a \"checkers game,\" where players (representatives) change often to reflect the latest moves (public opinion), while the Senate is more like a game of chess, with longer-term strategies?</p></div>",

    "q-027": "<p>Each of the 50 states has exactly <strong>two senators</strong> in the U.S. Senate, regardless of the state's geographical size or population.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Founding Fathers decided on two senators per state to ensure that smaller states wouldn't be overshadowed by larger ones, creating a \"balancing act\" in the Senate that has lasted since the Constitution was ratified in 1788?</p></div>",

    "q-028": "<p>Each state has two senators to ensure <strong>equal representation</strong> for both small and large states in the Senate.</p><p>During the drafting of the Constitution, the \"Great Compromise\" was reached: large states got representation by population in the House, and small states secured equal voices in the Senate.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the Founding Fathers debated representation, some states were so nervous about being overshadowed by larger states that they joked about secession; the solution was the Great Compromise, where every state gets two senators – a quirky balance that keeps the little guys from getting lost in the crowd!</p></div>",

    "q-029": "<p>The answer to this question <strong>varies depending on the specific congressional district you live in</strong>. Your district elects one Representative to advocate for your local community in Washington, D.C.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the House of Representatives was originally established with just 65 members in 1789? Today, it has grown to 435, each representing a unique district, making your local Representative a vital link between your community and the nation's capital!</p></div>",

    "q-030": "<p>The current Speaker of the House is <strong>Mike Johnson</strong>. The Speaker is the presiding officer of the House of Representatives and represents the majority political party in the House.</p><p>The Speaker is also second in the presidential line of succession, right after the Vice President.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the first Speaker of the House, Frederick Muhlenberg, was elected in 1789 and had to balance the interests of a fledgling nation? Since then, the Speaker has become a key player in American politics, with the power to shape legislation and influence the government!</p></div>",

    "q-031": "<p>A U.S. senator represents <strong>all the people of their state</strong>. Because they are elected statewide, their duty is to consider the needs and general welfare of their state as a whole.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the U.S. Senate was established in 1789, senators were originally chosen by state legislatures, not directly by the people, emphasizing their role as representatives of all citizens in their state, bridging local interests with national governance!</p></div>",

    "q-032": "<p>The <strong>citizens from their state</strong> elect U.S. senators.</p><p>Originally, state legislatures chose senators, but the 17th Amendment (passed in 1913) gave this power directly to the voting public of each state.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Before 1913, U.S. senators were chosen by state legislatures, which meant a lot of backroom deals and political maneuvering—imagine a game of poker where the stakes are your state's voice in Congress! The 17th Amendment changed the game, putting the power in the hands of the people.</p></div>",

    "q-033": "<p>A member of the House of Representatives represents only the <strong>citizens in their specific congressional district</strong>.</p><p>This makes them the federal politicians who are closest connected to local neighborhoods, counties, and small regions.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the U.S. Constitution was ratified in 1788, there were only 65 members in the House of Representatives, each representing an average of about 30,000 people? Today, that number has grown to over 700,000 citizens per representative, making local representation even more crucial!</p></div>",

    "q-034": "<p>The <strong>citizens in their specific congressional district</strong> elect members of the House of Representatives during the November general elections held every two years.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the House of Representatives was first established in 1789, each representative represented around 30,000 citizens? Today, that number has ballooned to over 700,000, making each vote in your district even more powerful in shaping national policy!</p></div>",

    "q-035": "<p>Some states have more representatives because of their <strong>population size</strong>.</p><p>States with many people, like California or Texas, receive dozens of representatives, while states with small populations, like Wyoming or Vermont, receive only one.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the U.S. Constitution was first ratified, the House of Representatives had just 65 members? Back then, states like Virginia had a massive population compared to tiny states like Delaware, highlighting how population has always shaped representation!</p></div>",

    "q-036": "<p>The President of the United States is elected for a term of <strong>four years</strong>. Presidential elections are always held in the month of November.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that George Washington set the two-term precedent for U.S. presidents, serving from 1789 to 1797? This tradition lasted until Franklin D. Roosevelt was elected to four terms, leading to the 22nd Amendment, which now limits presidents to just four years per term!</p></div>",

    "q-037": "<p>The 22nd Amendment limits the President to two terms to <strong>keep the President from becoming too powerful</strong>.</p><p>Before this amendment, Franklin D. Roosevelt was elected to four terms. After his presidency, the country decided that term limits were necessary to prevent anyone from ruling like a king indefinitely.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Franklin D. Roosevelt was the only U.S. president to serve more than two terms? His unprecedented four terms led to the 22nd Amendment, ensuring no future president could pull a \"Roosevelt\" and rule for life like a monarch!</p></div>",

    "q-038": "<p>The current President of the United States is <strong>Donald Trump</strong>. The President operates as the Head of State and the Head of Government for the United States.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Donald Trump, a businessman and reality TV star, became the 45th President of the United States in 2017, making him the first person to hold the presidency without prior military or government experience—a fact that surprised many and changed the political landscape!</p></div>",

    "q-039": "<p>The current Vice President of the United States is <strong>JD Vance</strong>. The Vice President also serves as the President of the Senate, breaking tie votes when necessary.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the role of Vice President was once seen as a \"political graveyard\"? John Adams, the first Vice President, famously said it was \"the most insignificant office that ever the invention of man contrived!\" Today, it’s a stepping stone to the presidency!</p></div>",

    "q-040": "<p>If the President dies, resigns, or is removed from office, the <strong>Vice President</strong> immediately becomes the President.</p><p>This transition ensures that the country always has continuous and stable leadership. Eight Vice Presidents have ascended to the presidency due to the death of a President.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When President William Henry Harrison died just 31 days into his term in 1841, Vice President John Tyler became the first to step up, famously declaring, \"I am the president,\" setting a crucial precedent for presidential succession!</p></div>",

    "q-041": "<p>The President has several pivotal powers. Important examples include the power to <strong>sign bills into law</strong>, the power to <strong>veto (reject) bills passes by Congress</strong>, and the role of <strong>Commander in Chief of the military</strong>.</p><p>The President also appoints federal judges and acts as the chief diplomat negotiating with foreign nations.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that President Franklin D. Roosevelt was the first to use the power to veto a bill on live radio in 1937? He made it a dramatic event, showcasing how a single decision by the President can shape the nation’s laws and policies!</p></div>",

    "q-042": "<p>The <strong>President of the United States</strong> is the Commander in Chief of the U.S. military.</p><p>This places ultimate control of the armed forces in the hands of a civilian leader, rather than a military general, to protect against military takeovers.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that George Washington, our first President and Commander in Chief, once led the Continental Army against the British during the Revolutionary War? His experience as a military leader helped shape the role of the president, ensuring that our armed forces would always be under civilian control!</p></div>",

    "q-043": "<p>The <strong>President</strong> must sign a bill passed by both the House and the Senate in order for it to officially become a federal law.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that in 1814, President James Madison had to flee the White House when the British invaded during the War of 1812? Despite the chaos, he still managed to sign crucial legislation, proving that even in tumultuous times, the President's role in making laws is vital!</p></div>",

    "q-044": "<p>The <strong>President</strong> has the power to veto (reject) a bill passed by Congress.</p><p>A veto stops the bill from becoming law, though Congress can occasionally override a presidential veto with a powerful two-thirds vote in both chambers.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that George Washington, the first U.S. President, used his veto power just twice during his entire presidency? He was cautious about vetoing bills, believing it should be reserved for truly significant issues, setting a precedent for future presidents!</p></div>",

    "q-045": "<p>The <strong>President of the United States</strong> nominates and appoints federal judges, including the justices of the Supreme Court.</p><p>However, the Senate must approve these appointments before the judges take office.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that George Washington, the first President, appointed all of the first 13 federal judges himself, setting a precedent that has shaped the judicial system ever since? Talk about starting strong—he literally had the fate of American justice in his hands!</p></div>",

    "q-046": "<p>The executive branch is massive. Its main parts include the <strong>President</strong>, the <strong>Vice President</strong>, and the <strong>President's Cabinet</strong>.</p><p>It also includes dozens of federal departments and agencies, like the FBI, the CIA, and the Department of Defense.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that George Washington, the first President, set the precedent for the Cabinet by gathering advisors to help him govern, which was so influential that it’s still a key part of the executive branch today?</p></div>",

    "q-047": "<p>The President's Cabinet <strong>advises the President</strong> on matters relating to the duties of their respective departments.</p><p>They are the President's closest and most trusted group of advisors, helping manage the country's defense, economy, and domestic policies.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know the first U.S. Cabinet meeting in 1789 included only four members: Thomas Jefferson, Alexander Hamilton, Henry Knox, and Edmund Randolph? This small but powerful group set the stage for the President's closest advisors to shape the nation’s future!</p></div>",

    "q-048": "<p>There are 15 main executive departments. Two prominent Cabinet-level positions are the <strong>Secretary of State</strong> (who handles foreign relations) and the <strong>Secretary of Defense</strong> (who manages the military).</p><p>Other roles include the Attorney General, Secretary of the Treasury, and Vice President.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Secretary of State position was first held by Thomas Jefferson, who famously said, \"The best government is the one that governs least\"? He shaped American diplomacy while juggling the complexities of a young nation and its foreign relations!</p></div>",

    "q-049": "<p>The Electoral College is important because <strong>it ultimately decides who is elected President</strong>.</p><p>The Founders created this system as a compromise between electing the President by a pure popular vote and having Congress choose the President. When Americans vote in November, they are actually voting for 'electors' who then cast the official votes for President.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that during the Constitutional Convention in 1787, some Founding Fathers were so worried about direct democracy that they compared it to \"mob rule,\" leading them to craft the Electoral College as a safeguard against the whims of the masses?</p></div>",

    "q-050": "<p>The <strong>Supreme Court</strong> is the most widely known part of the judicial branch.</p><p>In addition to the Supreme Court, the judicial branch includes all the lower federal courts and courts of appeals spread across the country.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Supreme Court was originally housed in a cramped room above the Old City Hall in Philadelphia, where justices had to share one table and a single window? It wasn't until 1935 that they moved into their grand building in Washington, D.C.!</p></div>",

    "q-051": "<p>The judicial branch <strong>reviews and interprets laws</strong> to explain their meaning.</p><p>Most importantly, the judicial branch decides if a law violates the U.S. Constitution (a process known as judicial review) and resolves disputes between states or citizens safely and fairly.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the concept of judicial review, which allows courts to invalidate laws that conflict with the Constitution, was established in 1803 by the landmark case Marbury v. Madison? This case set the stage for the judiciary to act as a check on the other branches of government!</p></div>",

    "q-052": "<p>The <strong>Supreme Court</strong> is the highest court in the United States.</p><p>Its rulings are the final word on legal interpretation, and no other court can overturn a Supreme Court decision.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Supreme Court started with just six justices in 1789? It was like a tiny legal team in a big game of constitutional chess, but now it has nine justices who make the ultimate calls on the rules of the game!</p></div>",

    "q-053": "<p>There are <strong>nine seats</strong> on the Supreme Court. The court consists of one Chief Justice and eight Associate Justices.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">The number of seats on the Supreme Court has changed over time, but it was set at nine in 1869—an odd number to avoid tie votes, much like a good basketball team needs an odd number of players to ensure a winner!</p></div>",

    "q-054": "<p>A simple majority of <strong>five justices</strong> is required to decide a case.</p><p>Because there are nine justices, having an odd number helps prevent tie votes on critical national issues.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Supreme Court was originally established with six justices in 1789, but it grew to nine by 1869? This odd number ensures that, like a referee in a game, there’s always a majority to keep the decision-making fair and decisive!</p></div>",

    "q-055": "<p>Supreme Court justices serve <strong>for life</strong>, meaning they keep their jobs until they retire, voluntarily step down, or pass away.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the first Supreme Court Justice, John Jay, voluntarily resigned after just six years to become a governor? This shows that while justices serve for life, they can choose to step down, making their tenure as flexible as it is enduring!</p></div>",

    "q-056": "<p>Justices serve for life so they can be <strong>independent of politics</strong>.</p><p>Without having to worry about running for reelection or being fired by angry politicians, judges can make fair decisions based entirely on the Constitution and the law, even if those decisions are unpopular.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the U.S. Constitution was being debated, some framers worried that judges might be swayed by political pressures, which is why they decided justices should serve for life? This way, they could boldly uphold justice, even if it ruffled a few political feathers!</p></div>",

    "q-057": "<p>The current Chief Justice of the United States is <strong>John Roberts</strong>. He presides over the Supreme Court's public sessions and sets the court's debate agenda.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that John Roberts, appointed by President George W. Bush in 2005, was only 50 years old at his confirmation, making him one of the youngest Chief Justices in U.S. history? His youth brings a fresh perspective to the highest court!</p></div>",

    "q-058": "<p>Under the Constitution, only the federal government has the power to <strong>print paper money, declare war, and make treaties with foreign countries</strong>.</p><p>These powers must be concentrated at the national level to ensure the country operates as one unified nation.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that before the Constitution was adopted, each state printed its own money, leading to chaos and confusion? It wasn't until the federal government took over printing money that the U.S. could finally have a consistent currency, helping to unite the nation!</p></div>",

    "q-059": "<p>Powers given specifically to the states include providing <strong>schooling and education, protection (police departments), and safety (fire departments)</strong>.</p><p>States also control their own roads and issue driver's licenses and zoning permits.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that in the early 1900s, some states had their own unique driving laws, like requiring drivers to stop and ask for directions from a local farmer? This quirky tradition shows just how much control states have over issuing driver's licenses and managing roads!</p></div>",

    "q-060": "<p>The 10th Amendment establishes <strong>states' rights</strong>. It dictates that any powers not specifically given to the federal government by the Constitution belong to the states or directly to the people.</p><p>This helps limit federal power and protects local governance.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the Constitution was first proposed, many feared a powerful central government, so the 10th Amendment was like a superhero cape for states, ensuring they could keep their own powers and protect local interests, making it a vital part of the Bill of Rights!</p></div>",

    "q-061": "<p>The governor is the leader of a state's executive branch. <strong>This answer varies depending on what state you live in.</strong> You can find your governor's name online.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the first governor of the English colony of Virginia, Sir William Berkeley, served from 1642 to 1652 and was known for his love of horse racing? This tradition of spirited leadership continues today, with each state having its own unique governor!</p></div>",

    "q-062": "<p>Each of the 50 states has its own capital city where the state government operates. <strong>This answer varies by state.</strong> (For example, the capital of New York is Albany; the capital of California is Sacramento).</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that some state capitals are not the largest cities in their states? For instance, Phoenix is the capital of Arizona, but Tucson is actually larger—showing that sometimes, history and geography take unexpected turns!</p></div>",

    "q-063": "<p>One important voting amendment is the 26th Amendment, which states that <strong>citizens eighteen (18) and older can vote</strong>.</p><p>Another is the 19th Amendment, which allowed women to vote, or the 24th Amendment, which eliminated poll taxes that were used to prevent poor or minority citizens from voting.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">In 1971, the 26th Amendment was ratified in just a few months, largely driven by the Vietnam War, where 18-year-olds could be drafted but couldn’t vote—talk about a major push for fairness!</p></div>",

    "q-064": "<p>Only <strong>U.S. citizens</strong> have the legal right to vote in federal elections, run for federal office, and serve on federal juries.</p><p>These are the primary responsibilities and privileges of active American citizenship.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the U.S. Constitution was ratified in 1788, only white male property owners could vote? It wasn't until the 15th Amendment in 1870 and the 19th Amendment in 1920 that voting rights expanded to include more citizens, showcasing the ongoing evolution of American democracy!</p></div>",

    "q-065": "<p>The Bill of Rights protects fundamental liberties for <em>everyone</em> living in the U.S., regardless of citizenship. Three of these rights are <strong>freedom of speech, freedom of religion, and freedom of assembly</strong>.</p><p>These ensure individuals can express themselves, pray how they wish, and gather together peacefully.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the First Amendment was inspired by the struggles of early American colonists who faced oppression from British rule? It was like giving a megaphone to the people, ensuring they could speak freely, practice any religion, and gather without fear—talk about a revolutionary idea!</p></div>",

    "q-066": "<p>When we say the Pledge of Allegiance, we show loyalty to <strong>the United States and to the American flag</strong>.</p><p>It is a promise to stand by the country and the principles of \"liberty and justice for all.\"</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">The Pledge of Allegiance was written in 1892 by Francis Bellamy, a Baptist minister, and originally included a salute that resembled a Nazi salute until it was changed in 1942, showing how loyalty can evolve over time!</p></div>",

    "q-067": "<p>When immigrants naturalize, they take the Oath of Allegiance. Two promises they make are to <strong>give up loyalty to other countries</strong> and to <strong>obey the laws of the United States</strong>.</p><p>They also promise to defend the U.S. Constitution and serve the military if required by law.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Oath of Allegiance dates back to the American Revolution? It was created to unite people who were fighting for freedom, ensuring that new citizens were committed to their new nation—just like soldiers pledging their loyalty before heading into battle!</p></div>",

    "q-068": "<p>People can become U.S. citizens automatically if they are <strong>born in the United States</strong>. For immigrants, the legal process of becoming a citizen is called <strong>naturalization</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the 14th Amendment, ratified in 1868, not only granted citizenship to former slaves but also established that anyone born on U.S. soil is automatically a citizen? This means that if you were born in a hospital in America, you have a special historical protection!</p></div>",

    "q-069": "<p>Civic participation means actively engaging in the community and democracy. Two examples are <strong>voting in elections</strong> and <strong>running for a political office</strong>.</p><p>Other examples include joining a political party, calling your elected officials, or volunteering in your town.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the first U.S. election in 1788 was a bit like a party? George Washington was the only candidate, and he won without a single vote being cast against him, showing that civic participation can sometimes be a unanimous affair!</p></div>",

    "q-070": "<p>Americans can serve their country in many ways, such as serving in the <strong>military</strong>, choosing to <strong>vote</strong>, and deciding to <strong>pay taxes</strong>.</p><p>Working for the local, state, or federal government is also a direct way to serve the nation.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that in 1776, when the Declaration of Independence was signed, only about 6% of Americans could vote? Today, voting is a key way for all citizens to actively participate in democracy and shape the future of their country!</p></div>",

    "q-071": "<p>Paying taxes is a <strong>required civic duty</strong> because taxes fund the entire operations of the federal government.</p><p>This money is necessary to pay for the military, national highways, federal programs, and the salaries of government workers.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the first federal income tax in the U.S. was introduced in 1861 to help fund the Civil War? It was a temporary measure, but it laid the groundwork for the tax system we know today!</p></div>",

    "q-072": "<p>Registering for the Selective Service is <strong>required by law</strong> for men ages 18-25.</p><p>If the country ever faces a massive crisis and requires a military draft, having this registry ensures that the draft process is fair and equitable to everyone.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Selective Service System has roots dating back to World War I? Over 2.8 million Americans were drafted during that war, and it shaped the way our nation prepares for military needs, emphasizing fairness and equity in times of crisis!</p></div>",

    "q-073": "<p>Colonists made the dangerous journey to America for many reasons. The most prominent were the search for <strong>religious freedom</strong>, <strong>political liberty</strong>, and the promise of new <strong>economic opportunities</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Pilgrims who landed at Plymouth Rock in 1620 were actually escaping from a place called Leyden in the Netherlands, where they felt their religious beliefs were being stifled? Their journey was fueled by the hope of practicing their faith freely in a new land!</p></div>",

    "q-074": "<p>Long before Christopher Columbus or European settlers arrived, the land was inhabited by <strong>Native Americans</strong> (also called American Indians or Indigenous Peoples).</p><p>There were thousands of complex and diverse indigenous societies across the continent.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Before European explorers set sail, the Americas were home to over 300 distinct languages and vibrant cultures, from the sophisticated city-builders of the Aztecs to the nomadic hunters of the Great Plains, showcasing a rich tapestry of life long before Columbus ever arrived!</p></div>",

    "q-075": "<p>Millions of people from <strong>Africa</strong> were kidnapped, taken across the Atlantic Ocean under brutal conditions, and sold into slavery in the Americas.</p><p>Enslaved Africans were forced to build early American infrastructure and work on massive agricultural plantations.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the journey of enslaved Africans, often called the Middle Passage, was so horrific that many preferred to jump overboard, believing they would rather face the unknown depths of the ocean than endure the brutal life of slavery?</p></div>",

    "q-076": "<p>The Americans fought the <strong>American Revolutionary War</strong> (also known as the War for Independence) to break free from the British Empire and King George III.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that during the American Revolutionary War, some soldiers wore the same uniforms as British troops, leading to moments of confusion on the battlefield? This quirky twist of fate showcased the chaotic nature of the fight for independence from British rule!</p></div>",

    "q-077": "<p>The Americans declared independence because of <strong>high taxes without representation</strong>.</p><p>The British government forced the colonists to pay heavy taxes (like on tea and paper) but refused to let the colonists have a voice or representative in the British Parliament.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Boston Tea Party was not just a protest, but a dramatic act where American colonists dressed as Native Americans and dumped 342 chests of British tea into Boston Harbor? This bold move was fueled by their frustration over \"taxation without representation\"!</p></div>",

    "q-078": "<p><strong>Thomas Jefferson</strong> was the primary author of the Declaration of Independence.</p><p>He was known as a brilliant writer, and his drafted words became the defining philosophy for the new United States.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Thomas Jefferson was only 33 years old when he penned the Declaration of Independence, and he famously wrote it in just a few weeks while staying up late, using a quill and ink—talk about a late-night writing session that changed the world!</p></div>",

    "q-079": "<p>The Declaration of Independence was universally adopted by the Continental Congress on <strong>July 4, 1776</strong>. This date is celebrated annually as America's birthday.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">On July 4, 1776, while the ink was still drying on the Declaration of Independence, John Adams predicted that this date would be celebrated as a great anniversary festival, complete with fireworks and festivities—talk about a prophetic party planner!</p></div>",

    "q-080": "<p>One of the most important events in the American Revolution was the <strong>writing of the Declaration of Independence</strong>.</p><p>Another major event was the Battle of Yorktown, where the British Army surrendered to George Washington, effectively ending the war.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when the Declaration of Independence was adopted on July 4, 1776, it was so bold that John Adams believed it would be celebrated with fireworks for generations? Fast forward, and it’s now our annual Independence Day celebration filled with parades and fireworks!</p></div>",

    "q-081": "<p>The United States initially started as 13 original colonies. Five of these original states were <strong>New York, Virginia, Massachusetts, Pennsylvania, and Maryland</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that New York was originally named New Amsterdam and was a Dutch trading post before the English took over? Meanwhile, Virginia is often called the \"Mother of Presidents\" because it produced eight U.S. presidents, more than any other state!</p></div>",

    "q-082": "<p>The <strong>U.S. Constitution</strong> was written in the summer of 1787 in Philadelphia. The Founding Fathers drafted it to replace the weak Articles of Confederation and create a stronger central government.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">In a hot summer of 1787, the Founding Fathers locked themselves in Independence Hall, where they debated and crafted the U.S. Constitution, fueled by coffee and a desire to create a \"more perfect union\"—talk about a productive heatwave!</p></div>",

    "q-083": "<p>The Federalist Papers were written under the pen name \"Publius.\" The actual writers were <strong>Alexander Hamilton, James Madison, and John Jay</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Alexander Hamilton, James Madison, and John Jay wrote The Federalist Papers to convince New Yorkers to ratify the Constitution? Hamilton penned the majority of the essays, showcasing his passion for a strong central government—talk about a founding father with a flair for persuasion!</p></div>",

    "q-084": "<p>The Federalist Papers were a series of highly influential newspaper articles. They were critical because they effectively <strong>convinced the American people to support and ratify the new U.S. Constitution</strong> by explaining how the new government would work.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">The Federalist Papers were penned by three founding fathers—Alexander Hamilton, James Madison, and John Jay—under the catchy pseudonym \"Publius,\" turning them into the original celebrity authors of American political thought, much like a revolutionary blog that shaped a nation!</p></div>",

    "q-085": "<p><strong>Benjamin Franklin</strong> was one of the nation's most famous Founding Fathers.</p><p>He was a brilliant U.S. diplomat sent to France, the oldest member of the Constitutional Convention, an inventor, and he famously started the first free public library in America.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Benjamin Franklin not only helped draft the Declaration of Independence, but he also had a knack for innovation, inventing items like the lightning rod and bifocals, proving that he truly was a \"founding father\" of both the nation and modern conveniences!</p></div>",

    "q-086": "<p><strong>George Washington</strong> is often referred to as the \"Father of Our Country.\"</p><p>He was the deeply respected General who led the Continental Army to victory during the Revolutionary War, and he later became the very first President of the United States.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">George Washington was so influential that when he was elected as the first President, he set a precedent for the office by voluntarily stepping down after two terms, proving that even the \"Father of Our Country\" believed in the importance of democratic leadership!</p></div>",

    "q-087": "<p><strong>Thomas Jefferson</strong> is famously the primary author of the Declaration of Independence. He later served as the third U.S. President and executed the massive Louisiana Purchase.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Thomas Jefferson, a passionate gardener and inventor, not only penned the Declaration of Independence but also brought back French culture to America by introducing new crops like tomatoes and potatoes, transforming American cuisine forever!</p></div>",

    "q-088": "<p><strong>James Madison</strong> is known as the \"Father of the Constitution\" because of his pivotal role in drafting the document and the Bill of Rights. He also served as the fourth U.S. President during the War of 1812.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">James Madison, standing at just 5'4\" and weighing only 100 pounds, was the smallest U.S. President, yet his monumental ideas shaped the Constitution and the Bill of Rights, earning him the title \"Father of the Constitution\" despite his diminutive stature!</p></div>",

    "q-089": "<p><strong>Alexander Hamilton</strong> was the passionate first Secretary of the Treasury who established America's financial system. He was also an important aide to George Washington and a primary writer of the Federalist Papers.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Alexander Hamilton, who famously put America on the financial map, also had a fierce rivalry with Thomas Jefferson that sparked the first political parties? Their debates were so intense that they laid the groundwork for our modern political landscape!</p></div>",

    "q-090": "<p>In 1803, President Thomas Jefferson orchestrated the <strong>Louisiana Purchase</strong>, buying the vast Louisiana Territory from France.</p><p>This massive land deal doubled the size of the United States overnight, expanding the nation westward.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">The Louisiana Purchase in 1803 was such a steal that it cost the U.S. just about four cents per acre, making it one of the best real estate deals in history—imagine buying the entire state of Texas for a mere $15!</p></div>",

    "q-091": "<p>During the 1800s, the U.S. engaged in several major wars. These included the <strong>Civil War</strong>, the <strong>War of 1812</strong>, and the <strong>Mexican-American War</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that during the Mexican-American War, American troops were led by future Civil War heroes like Ulysses S. Grant and Robert E. Lee? This conflict not only expanded U.S. territory but also shaped the military careers of many who would later fight on the opposite sides in the Civil War!</p></div>",

    "q-092": "<p>The war fought between the Northern states (the Union) and the Southern states (the Confederacy) is known as the <strong>Civil War</strong>. It lasted from 1861 to 1865.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Civil War was not just a battle over territory but also a clash of cultures, with the North favoring industry and the South clinging to agriculture and slavery? This stark divide made the war a dramatic turning point in American history!</p></div>",

    "q-093": "<p>A critically important event of the Civil War was the issuing of the <strong>Emancipation Proclamation</strong> by President Abraham Lincoln, which declared slaves in the rebelling states to be free.</p><p>Another major event was the Battle of Gettysburg, a turning point that led to the North's victory.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Emancipation Proclamation not only freed slaves in the Confederate states but also allowed African Americans to fight in the Union Army? By the end of the war, around 180,000 Black soldiers had bravely served, significantly contributing to the North's victory!</p></div>",

    "q-094": "<p><strong>Abraham Lincoln</strong> is celebrated as one of America's greatest presidents. He successfully led the United States through its darkest hour—the Civil War—and he issued the Emancipation Proclamation, which began the process of ending slavery.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Abraham Lincoln was a champion wrestler in his youth? Known for his strength and agility, he earned a reputation as a formidable opponent, which might explain his tenacity in fighting for the Union during the Civil War!</p></div>",

    "q-095": "<p>The <strong>Emancipation Proclamation</strong> was a presidential order that declared all enslaved people within the rebelling Confederate states to be legally free.</p><p>While it did not immediately free all slaves everywhere, it fundamentally changed the moral purpose of the American Civil War.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When President Lincoln issued the Emancipation Proclamation in 1863, he not only freed enslaved people in the Confederate states but also transformed the Civil War from a battle for the Union into a fight for freedom, making it a moral crusade that inspired countless abolitionists!</p></div>",

    "q-096": "<p>The <strong>Civil War</strong> was the bloody national conflict that ultimately resulted in the defeat of the South and the permanent abolition of legal slavery throughout the United States.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that during the Civil War, one of the most famous songs was \"Battle Hymn of the Republic\"? It wasn't just a catchy tune; it became a rallying cry for Union soldiers who fought not only for their country but also for the freedom of enslaved people!</p></div>",

    "q-097": "<p>The <strong>14th Amendment</strong> is one of the most important additions to the Constitution. Passed after the Civil War, it guaranteed that anyone born or naturalized in the U.S. is a citizen, securing the rights of formerly enslaved Black Americans.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">The 14th Amendment, ratified in 1868, was so powerful that it turned the phrase \"We the People\" into a promise that everyone born or naturalized in the U.S. is included, making it a key victory in the ongoing struggle for civil rights!</p></div>",

    "q-098": "<p>All men gained the right to vote following the Civil War with the ratification of the <strong>15th Amendment</strong> in 1870.</p><p>It legally stated that a citizen could not be denied the right to vote based on \"race, color, or previous condition of servitude.\"</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Imagine a world where your voting rights hung by a thread! After the Civil War, the 15th Amendment in 1870 boldly declared that no one could be denied the vote based on race, paving the way for millions of men to finally have their say in democracy.</p></div>",

    "q-099": "<p>Two of the most famous leaders of the early women's rights movement in the 1800s were <strong>Susan B. Anthony</strong> and <strong>Elizabeth Cady Stanton</strong>. They fought tirelessly for decades to secure voting rights for women.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Susan B. Anthony and Elizabeth Cady Stanton were such a dynamic duo that they organized the first Women’s Rights Convention in Seneca Falls in 1848, where they boldly declared, \"We hold these truths to be self-evident: that all men and women are created equal!\"</p></div>",

    "q-100": "<p>During the 1900s, the United States became a global superpower and fought in several massive conflicts. Major examples include <strong>World War I, World War II, the Korean War, and the Vietnam War</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that in World War II, the U.S. dropped atomic bombs on Japan, leading to the end of the war, but also sparking a fierce debate about ethics in warfare that continues to this day? It's a pivotal moment that changed global politics forever!</p></div>",

    "q-101": "<p>The United States entered <strong>World War I</strong> largely because Germany began using submarines to attack American civilian passenger ships without warning.</p><p>Additionally, the \"Zimmerman Telegram\" revealed Germany was trying to encourage Mexico to attack the U.S.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that one of the ships sunk by German U-boats was the Lusitania, which carried not just passengers but also munitions? This attack fueled American outrage and helped turn public opinion decisively against Germany, paving the way for U.S. involvement in World War I!</p></div>",

    "q-102": "<p>All American women finally won the constitutional right to vote in <strong>1920</strong>, decades after the women's rights movement began, through the passage of the 19th Amendment.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">In 1920, when the 19th Amendment was ratified, American women celebrated their newfound right to vote by throwing the largest party in history, complete with parades and rallies—proving that a century-long fight for equality was worth celebrating with style!</p></div>",

    "q-103": "<p>The <strong>Great Depression</strong> was the worst economic disaster in modern history. Unemployment skyrocketed to 25%, banks completely entirely, and millions of Americans lost their homes, farms, and life savings.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">During the Great Depression, bread lines became a common sight, but did you know that some people resorted to using \"Hoovervilles,\" makeshift shantytowns named after President Hoover, to symbolize their frustration with his inaction? It was a tough time that shaped America's economic policies for decades!</p></div>",

    "q-104": "<p>The Great Depression is triggered by the devastating <strong>Stock Market Crash of 1929</strong>.</p><p>Over a few days in October 1929, the stock market completely collapsed, wiping out millions of investors and plunging the global economy into crisis.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the stock market crashed in October 1929, it was so sudden that it was nicknamed Black Tuesday, and it not only wiped out fortunes but also ushered in a decade-long economic roller coaster that left a lasting mark on American history!</p></div>",

    "q-105": "<p><strong>Franklin D. Roosevelt</strong> (often called FDR) was the U.S. President who led the nation through two of the country's greatest crises: the Great Depression of the 1930s and World War II in the 1940s.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Franklin D. Roosevelt was the only U.S. president to serve four terms, and his iconic fireside chats not only comforted Americans during the Great Depression but also inspired hope as the nation prepared for World War II, making him a true beacon in turbulent times!</p></div>",

    "q-106": "<p>The United States entered World War II after <strong>Japan launched a surprise military attack on the U.S. naval base at Pearl Harbor, Hawaii</strong> on December 7, 1941.</p><p>The devastating attack killed over 2,400 Americans and destroyed the Pacific Fleet.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">On December 7, 1941, while many Americans were enjoying a peaceful Sunday morning, Japan's attack on Pearl Harbor shocked the nation, leading to President Franklin D. Roosevelt's famous declaration that day would \"live in infamy\" as the U.S. rallied to join the fight in World War II!</p></div>",

    "q-107": "<p>Before becoming the 34th U.S. President, <strong>Dwight D. Eisenhower</strong> was a brilliant 5-star military general. He famously served as the Supreme Commander of Allied Forces in Europe during World War II, organizing the D-Day invasion.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Dwight D. Eisenhower was so pivotal in World War II that after orchestrating the daring D-Day invasion, he earned the nickname \"Ike,\" which not only became a household name for him but also inspired a popular sandwich called the \"Ike,\" filled with delicious ingredients just like his complex military strategies!</p></div>",

    "q-108": "<p>During the decades-long Cold War, the main global rival to the United States was the <strong>Soviet Union</strong> (or the USSR).</p><p>The era was defined by a massive geopolitical clash between American capitalism/democracy and Soviet communism.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">During the Cold War, the United States and the Soviet Union were like two heavyweight boxers in a ring, each trying to outsmart the other, with everything from space races to nuclear arms creating a high-stakes game of global chess that kept the world on edge!</p></div>",

    "q-109": "<p>The overarching concern of the United States during the Cold War was <strong>stopping the global spread of communism</strong>.</p><p>America engaged in numerous proxy wars, intelligence operations, and economic initiatives (like the Marshall Plan) to contain Soviet influence.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">During the Cold War, the U.S. was so worried about communism spreading that it even created a \"Domino Theory,\" believing that if one country fell to communism, neighboring countries would follow like dominoes—a dramatic game of global geopolitics!</p></div>",

    "q-110": "<p>The United States entered the <strong>Korean War</strong> in 1950 to defend democratic South Korea after it was invaded by communist North Korea, who was backed by the Soviet Union and China.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">The Korean War is often called \"The Forgotten War\" because it didn't get as much attention as WWII or Vietnam, yet it was a crucial showdown in the Cold War, where U.S. troops fought under the banner of the United Nations to stop the spread of communism in Asia!</p></div>",

    "q-111": "<p>Similar to the Korean War, the U.S. entered the <strong>Vietnam War</strong> to stop the spread of communism in Southeast Asia.</p><p>America supported South Vietnam in an attempt to prevent communist North Vietnam (backed by the Soviet Union) from taking over the region.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">During the Vietnam War, the U.S. dropped more bombs than it did in all of World War II combined, making it a crucial chapter in the fight against communism that turned the jungle into a battleground of both military strategy and cultural upheaval!</p></div>",

    "q-112": "<p>The <strong>civil rights movement</strong> was a monumental struggle in the 1950s and 60s designed to end racial discrimination and legally enforced segregation.</p><p>The movement secured critical victories, such as the Civil Rights Act of 1964 and the Voting Rights Act of 1965, ensuring equal rights for Black Americans.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that during the civil rights movement, the famous \"I Have a Dream\" speech by Martin Luther King Jr. was delivered in front of over 250,000 people at the 1963 March on Washington? It became a defining moment, inspiring change and solidarity in the fight against racial discrimination!</p></div>",

    "q-113": "<p><strong>Martin Luther King, Jr.</strong> was the most prominent leader of the civil rights movement.</p><p>A brilliant orator and advocate for nonviolent protest, he famously delivered the \"I Have a Dream\" speech during the March on Washington, demanding equality and racial justice.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Martin Luther King, Jr. was inspired by Mahatma Gandhi's nonviolent approach? His famous \"I Have a Dream\" speech, delivered to over 250,000 people in 1963, has become one of the most quoted speeches in history, echoing the call for equality and justice!</p></div>",

    "q-114": "<p>The U.S. entered the <strong>Persian Gulf War</strong> in 1991 to repel the Iraqi military.</p><p>Iraqi dictator Saddam Hussein had invaded the small, oil-rich neighboring country of Kuwait, and an American-led coalition was formed to liberate it and restore its sovereignty.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">In a dramatic twist, after Iraq's invasion of Kuwait, the U.S. quickly assembled a coalition of 34 nations, proving that sometimes it takes a global team effort—like a supercharged soccer match—to kick an aggressor off the field and restore peace!</p></div>",

    "q-115": "<p>On the morning of <strong>September 11, 2001</strong>, terrorists hijacked four commercial airplanes. They crashed two of them into the Twin Towers in New York City and one into the Pentagon.</p><p>Nearly 3,000 people were killed in the deadliest terrorist attack in world history.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">On September 11, 2001, as the world watched in shock, the Twin Towers—once symbols of economic power—became part of a pivotal moment in history, leading to major global changes in security and international relations, forever marking the date as \"9/11.\"</p></div>",

    "q-116": "<p>In response to the horrific 9/11 terror attacks, the United States launched the \"War on Terror.\" This sparked long and complex military conflicts including the <strong>War in Afghanistan</strong> and later the <strong>War in Iraq</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the War in Afghanistan, which began in 2001, became the longest-running conflict in U.S. history, outlasting both World War I and World War II? It’s a testament to the complexities of modern warfare and global politics!</p></div>",

    "q-117": "<p>The United States legally recognizes hundreds of sovereign Native American nations. Some of the well-known tribes include the <strong>Navajo, Cherokee, Cheyenne, Sioux, and Apache</strong> tribes, all possessing rich histories and cultures long predating European colonization.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">The Navajo Nation is the largest Native American tribe in the U.S., spanning over 27,000 square miles—larger than the state of West Virginia! Their rich culture includes weaving intricate rugs and speaking a unique language that was famously used as a code during World War II.</p></div>",

    "q-118": "<p>American inventors have profoundly shaped the modern world. Major American innovations include the invention of the <strong>lightbulb, the airplane, the telephone, the integrated circuit, and the internet</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Thomas Edison, often credited with inventing the light bulb, actually improved on existing designs? His version lit up the world in 1879 and sparked a revolution in how we live, work, and play—literally brightening our days and nights!</p></div>",

    "q-119": "<p><strong>Washington, D.C.</strong> is the capital of the United States.</p><p>It is a unique federal district designed specifically to house the center of the American government, including the White House, the U.S. Capitol, and the Supreme Court.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that when Washington, D.C. was established in 1790, it was chosen as a compromise location between the North and South, and the land was actually taken from Maryland and Virginia? This unique city was built from scratch to serve as the nation's capital!</p></div>",

    "q-120": "<p>The <strong>Statue of Liberty</strong> stands in the waters of New York Harbor, located on Liberty Island next to New York City.</p><p>The majestic copper statue was gifted by France in 1886 and has long stood as an iconic symbol of freedom and welcome to immigrants arriving by sea.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that the Statue of Liberty was originally meant to be a lighthouse? Designed by French sculptor Frédéric Auguste Bartholdi, it stands 151 feet tall and was a gift from France to celebrate American independence and friendship, lighting the way for millions of immigrants!</p></div>",

    "q-121": "<p>The American flag has <strong>13 stripes</strong> (seven red and six white) specifically to represent the original 13 American colonies that declared their independence from Great Britain in 1776, founding the nation.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the colonies declared independence, they were like a rebellious teenager breaking free from parental control—hence, the 13 stripes on the flag symbolize these original colonies' bold leap toward freedom and self-governance!</p></div>",

    "q-122": "<p>The American flag features exactly <strong>50 stars</strong> on a blue background because there is one star representing each of the 50 individual states that currently make up the United States.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the U.S. flag was first adopted in 1777, it had just 13 stripes and stars representing the original colonies, but as the nation expanded, each new state earned its very own star, leading to today's 50-star flag, which symbolizes the unity and diversity of all states!</p></div>",

    "q-123": "<p><strong>\"The Star-Spangled Banner\"</strong> is the official national anthem of the United States.</p><p>The moving lyrics were penned by Francis Scott Key during the War of 1812 after he witnessed an American fort surviving a brutal overnight British naval bombardment.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that \"The Star-Spangled Banner\" was inspired by a flag so large that it could be seen from miles away? Francis Scott Key was so moved by the sight of it waving after a fierce battle that he turned his emotions into the beloved anthem we sing today!</p></div>",

    "q-124": "<p>\"E Pluribus Unum\" is a famous Latin phrase meaning <strong>\"Out of many, one.\"</strong></p><p>It beautifully illustrates the core American ideal: a single, unified nation forged from many diverse states, cultures, and peoples.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that \"E Pluribus Unum\" was originally suggested as the motto for the United States in 1782, during the Revolutionary War? It reflects the unity of the thirteen colonies coming together to form one powerful nation, much like a tasty stew made from many ingredients!</p></div>",

    "q-125": "<p><strong>Independence Day</strong> is the most important national holiday celebrating America's birth.</p><p>Held annually on July 4th, it marks the exact day in 1776 when the Continental Congress adopted the Declaration of Independence, finalizing the break from British rule.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">When the Declaration of Independence was signed on July 4, 1776, some of the Founding Fathers were so excited they fired off cannons and rang church bells, setting the stage for the fireworks and festivities we enjoy today to celebrate America's birthday!</p></div>",

    "q-126": "<p>There are several prominent national U.S. holidays recognized by the government. Examples include <strong>Thanksgiving, Christmas Day, Memorial Day, Martin Luther King Jr. Day, and Independence Day</strong>.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Did you know that Thanksgiving dates back to 1621 when Pilgrims and Native Americans shared a feast, but it wasn’t until 1863 that President Lincoln declared it a national holiday to foster unity during the Civil War? Now that's a reason to celebrate!</p></div>",

    "q-127": "<p><strong>Memorial Day</strong>, observed annually on the last Monday of May, is a solemn national holiday.</p><p>It is dedicated entirely to honoring, remembering, and mourning the brave men and women who have died while serving in the U.S. Armed Forces.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Memorial Day originated after the Civil War as \"Decoration Day,\" when people decorated the graves of fallen soldiers, and it wasn’t until 1971 that it became a federal holiday, making it a three-day weekend for many to honor the heroes who sacrificed for their country!</p></div>",

    "q-128": "<p><strong>Veterans Day</strong>, celebrated every year on November 11th, is a distinct national holiday.</p><p>While Memorial Day honors the fallen, Veterans Day honors and thanks <em>all</em> military veterans (living and deceased) who have served honorably in the United States Armed Forces during times of both war and peace.</p><div class=\"mt-4 pt-4 border-t border-border/50\"><h4 class=\"font-semibold text-primary mb-2 flex items-center gap-1.5\">&#128DCDC; Fun History Fact</h4><p class=\"text-sm opacity-90\">Veterans Day originated as Armistice Day in 1919, marking the end of World War I; it was renamed in 1954 to honor all veterans, so now, instead of just celebrating the end of a war, we celebrate the bravery of those who serve, no matter the time or place!</p></div>"
};
