import type { CivicsQuestion } from "@/lib/domain/civics";

export const CIVICS_BANK_VERSION = "2025-v2-128q";

export const QUESTION_BANK: CivicsQuestion[] = [
  // A: Principles of American Government
  {
    id: "q-001",
    prompt: "What is the form of government of the United States?",
    acceptedAnswers: ["republic", "constitution-based federal republic", "representative democracy", "constitutional republic", "federal republic"],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-002",
    prompt: "What is the supreme law of the land?",
    acceptedAnswers: ["the constitution", "u.s. constitution", "constitution"],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: true,
  },
  {
    id: "q-003",
    prompt: "Name one thing the U.S. Constitution does.",
    acceptedAnswers: [
      "forms the government",
      "defines powers of government",
      "defines the parts of government",
      "protects the rights of the people",
      "sets up the government",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-004",
    prompt: 'The U.S. Constitution starts with the words "We the People." What does "We the People" mean?',
    acceptedAnswers: [
      "self-government",
      "popular sovereignty",
      "consent of the governed",
      "people should govern themselves",
      "social contract",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-005",
    prompt: "How are changes made to the U.S. Constitution?",
    acceptedAnswers: ["amendments", "the amendment process", "amendment"],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-006",
    prompt: "What does the Bill of Rights protect?",
    acceptedAnswers: [
      "the basic rights of americans",
      "the basic rights of people living in the united states",
      "basic rights of americans",
      "rights of the people",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-007",
    prompt: "How many amendments does the U.S. Constitution have?",
    acceptedAnswers: ["27", "twenty-seven", "twenty seven"],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: true,
  },
  {
    id: "q-008",
    prompt: "Why is the Declaration of Independence important?",
    acceptedAnswers: [
      "it says america is free from british control",
      "it says all people are created equal",
      "it identifies inherent rights",
      "it identifies individual freedoms",
      "announced our independence from britain",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-009",
    prompt: "What founding document said the American colonies were free from Britain?",
    acceptedAnswers: ["declaration of independence", "the declaration of independence"],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-010",
    prompt: "Name two important ideas from the Declaration of Independence and the U.S. Constitution.",
    acceptedAnswers: [
      "equality",
      "liberty",
      "social contract",
      "natural rights",
      "limited government",
      "self-government",
      "equality and liberty",
      "liberty and self-government",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-011",
    prompt: 'The words "Life, Liberty, and the pursuit of Happiness" are in what founding document?',
    acceptedAnswers: ["declaration of independence", "the declaration of independence"],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-012",
    prompt: "What is the economic system of the United States?",
    acceptedAnswers: ["capitalism", "free market economy", "capitalist economy", "market economy"],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: true,
  },
  {
    id: "q-013",
    prompt: "What is the rule of law?",
    acceptedAnswers: [
      "everyone must follow the law",
      "leaders must obey the law",
      "government must obey the law",
      "no one is above the law",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-014",
    prompt: "Many documents influenced the U.S. Constitution. Name one.",
    acceptedAnswers: [
      "declaration of independence",
      "articles of confederation",
      "federalist papers",
      "anti-federalist papers",
      "virginia declaration of rights",
      "fundamental orders of connecticut",
      "mayflower compact",
      "iroquois great law of peace",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  {
    id: "q-015",
    prompt: "There are three branches of government. Why?",
    acceptedAnswers: [
      "so one part does not become too powerful",
      "checks and balances",
      "separation of powers",
    ],
    isDynamicOfficial: false,
    category: "Principles of American Government",
    isSpecial65: false,
  },
  // B: System of Government
  {
    id: "q-016",
    prompt: "Name the three branches of government.",
    acceptedAnswers: [
      "legislative, executive, and judicial",
      "congress, president, and the courts",
      "legislative executive judicial",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-017",
    prompt: "The President of the United States is in charge of which branch of government?",
    acceptedAnswers: ["executive branch", "the executive branch", "executive"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-018",
    prompt: "What part of the federal government writes laws?",
    acceptedAnswers: ["congress", "u.s. congress", "the legislature", "legislative branch"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-019",
    prompt: "What are the two parts of the U.S. Congress?",
    acceptedAnswers: [
      "senate and house of representatives",
      "the senate and house",
      "senate and house",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-020",
    prompt: "Name one power of the U.S. Congress.",
    acceptedAnswers: ["writes laws", "declares war", "makes the federal budget", "make laws", "declare war"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-021",
    prompt: "How many U.S. senators are there?",
    acceptedAnswers: ["100", "one hundred"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-022",
    prompt: "How long is a term for a U.S. senator?",
    acceptedAnswers: ["six years", "6 years", "6", "six"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-023",
    prompt: "Who is one of your state's U.S. senators now?",
    acceptedAnswers: ["answers will vary", "varies by state"],
    isDynamicOfficial: true,
    dynamicType: "SENATOR",
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-024",
    prompt: "How many voting members are in the House of Representatives?",
    acceptedAnswers: ["435", "four hundred thirty-five", "four hundred thirty five"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-025",
    prompt: "How long is a term for a member of the House of Representatives?",
    acceptedAnswers: ["two years", "2 years", "2", "two"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-026",
    prompt: "Why do U.S. representatives serve shorter terms than U.S. senators?",
    acceptedAnswers: ["to more closely follow public opinion", "follow public opinion"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-027",
    prompt: "How many senators does each state have?",
    acceptedAnswers: ["two", "2"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-028",
    prompt: "Why does each state have two senators?",
    acceptedAnswers: [
      "equal representation for small states",
      "the great compromise",
      "connecticut compromise",
      "equal representation",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-029",
    prompt: "Name your U.S. representative.",
    acceptedAnswers: ["answers will vary", "varies by district"],
    isDynamicOfficial: true,
    dynamicType: "REPRESENTATIVE",
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-030",
    prompt: "What is the name of the Speaker of the House of Representatives now?",
    acceptedAnswers: ["mike johnson", "johnson"],
    isDynamicOfficial: true,
    dynamicType: "SPEAKER",
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-031",
    prompt: "Who does a U.S. senator represent?",
    acceptedAnswers: ["citizens of their state", "people of their state", "all people of their state"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-032",
    prompt: "Who elects U.S. senators?",
    acceptedAnswers: ["citizens from their state", "the people of their state", "voters in their state"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-033",
    prompt: "Who does a member of the House of Representatives represent?",
    acceptedAnswers: [
      "citizens in their congressional district",
      "citizens in their district",
      "people from their congressional district",
      "people in their district",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-034",
    prompt: "Who elects members of the House of Representatives?",
    acceptedAnswers: [
      "citizens from their congressional district",
      "voters in their district",
      "citizens in their district",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-035",
    prompt: "Some states have more representatives than other states. Why?",
    acceptedAnswers: [
      "because of the state's population",
      "they have more people",
      "some states have more people",
      "population",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-036",
    prompt: "The President of the United States is elected for how many years?",
    acceptedAnswers: ["four years", "4 years", "4", "four"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-037",
    prompt: "The President of the United States can serve only two terms. Why?",
    acceptedAnswers: [
      "because of the 22nd amendment",
      "to keep the president from becoming too powerful",
      "22nd amendment",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-038",
    prompt: "What is the name of the President of the United States now?",
    acceptedAnswers: ["donald trump", "trump"],
    isDynamicOfficial: true,
    dynamicType: "PRESIDENT",
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-039",
    prompt: "What is the name of the Vice President of the United States now?",
    acceptedAnswers: ["jd vance", "vance", "j.d. vance"],
    isDynamicOfficial: true,
    dynamicType: "VICE_PRESIDENT",
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-040",
    prompt: "If the president can no longer serve, who becomes president?",
    acceptedAnswers: [
      "the vice president",
      "vice president",
      "the vice president of the united states",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-041",
    prompt: "Name one power of the president.",
    acceptedAnswers: [
      "signs bills into law",
      "vetoes bills",
      "enforces laws",
      "commander in chief",
      "chief diplomat",
      "appoints federal judges",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-042",
    prompt: "Who is Commander in Chief of the U.S. military?",
    acceptedAnswers: ["the president", "president of the united states", "the president of the united states"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-043",
    prompt: "Who signs bills to become laws?",
    acceptedAnswers: ["the president", "president of the united states"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-044",
    prompt: "Who vetoes bills?",
    acceptedAnswers: ["the president", "president of the united states"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-045",
    prompt: "Who appoints federal judges?",
    acceptedAnswers: ["the president", "president of the united states"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-046",
    prompt: "The executive branch has many parts. Name one.",
    acceptedAnswers: ["president", "cabinet", "federal departments and agencies", "vice president"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-047",
    prompt: "What does the President's Cabinet do?",
    acceptedAnswers: ["advises the president", "advise the president"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-048",
    prompt: "What are two Cabinet-level positions?",
    acceptedAnswers: [
      "attorney general",
      "secretary of state",
      "secretary of defense",
      "secretary of the treasury",
      "secretary of homeland security",
      "vice president",
      "secretary of agriculture",
      "secretary of education",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-049",
    prompt: "Why is the Electoral College important?",
    acceptedAnswers: [
      "it decides who is elected president",
      "it provides a compromise between the popular election of the president and congressional selection",
      "elects the president",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-050",
    prompt: "What is one part of the judicial branch?",
    acceptedAnswers: ["supreme court", "federal courts", "the supreme court"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-051",
    prompt: "What does the judicial branch do?",
    acceptedAnswers: [
      "reviews laws",
      "explains laws",
      "resolves disputes about the law",
      "decides if a law goes against the constitution",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-052",
    prompt: "What is the highest court in the United States?",
    acceptedAnswers: ["supreme court", "the supreme court"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-053",
    prompt: "How many seats are on the Supreme Court?",
    acceptedAnswers: ["nine", "9"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-054",
    prompt: "How many Supreme Court justices are usually needed to decide a case?",
    acceptedAnswers: ["five", "5"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-055",
    prompt: "How long do Supreme Court justices serve?",
    acceptedAnswers: ["for life", "lifetime appointment", "until retirement", "life"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-056",
    prompt: "Supreme Court justices serve for life. Why?",
    acceptedAnswers: [
      "to be independent of politics",
      "to limit outside political influence",
      "independent of politics",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-057",
    prompt: "Who is the Chief Justice of the United States now?",
    acceptedAnswers: ["john roberts", "roberts"],
    isDynamicOfficial: true,
    dynamicType: "CHIEF_JUSTICE",
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-058",
    prompt: "Name one power that is only for the federal government.",
    acceptedAnswers: [
      "print paper money",
      "mint coins",
      "declare war",
      "create an army",
      "make treaties",
      "set foreign policy",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-059",
    prompt: "Name one power that is only for the states.",
    acceptedAnswers: [
      "provide schooling and education",
      "provide protection police",
      "provide safety fire departments",
      "give a driver's license",
      "approve zoning and land use",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-060",
    prompt: "What is the purpose of the 10th Amendment?",
    acceptedAnswers: [
      "powers not given to the federal government belong to the states or to the people",
      "states' rights",
      "reserved powers to the states",
    ],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  {
    id: "q-061",
    prompt: "Who is the governor of your state now?",
    acceptedAnswers: ["answers will vary", "varies by state"],
    isDynamicOfficial: true,
    dynamicType: "GOVERNOR",
    category: "System of Government",
    isSpecial65: true,
  },
  {
    id: "q-062",
    prompt: "What is the capital of your state?",
    acceptedAnswers: ["answers will vary", "varies by state"],
    isDynamicOfficial: false,
    category: "System of Government",
    isSpecial65: false,
  },
  // C: Rights and Responsibilities
  {
    id: "q-063",
    prompt: "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.",
    acceptedAnswers: [
      "citizens eighteen and older can vote",
      "you don't have to pay a poll tax to vote",
      "any citizen can vote",
      "a male citizen of any race can vote",
      "18 and older can vote",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-064",
    prompt: "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?",
    acceptedAnswers: ["citizens", "citizens of the united states", "u.s. citizens", "american citizens"],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-065",
    prompt: "What are three rights of everyone living in the United States?",
    acceptedAnswers: [
      "freedom of expression",
      "freedom of speech",
      "freedom of assembly",
      "freedom to petition the government",
      "freedom of religion",
      "the right to bear arms",
      "speech religion assembly",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-066",
    prompt: "What do we show loyalty to when we say the Pledge of Allegiance?",
    acceptedAnswers: ["the united states", "the flag", "united states and flag"],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: true,
  },
  {
    id: "q-067",
    prompt: "Name two promises that new citizens make in the Oath of Allegiance.",
    acceptedAnswers: [
      "give up loyalty to other countries",
      "defend the constitution",
      "obey the laws of the united states",
      "serve in the military if needed",
      "be loyal to the united states",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-068",
    prompt: "How can people become United States citizens?",
    acceptedAnswers: [
      "be born in the united states",
      "naturalize",
      "derive citizenship",
      "naturalization",
      "born in the united states",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-069",
    prompt: "What are two examples of civic participation in the United States?",
    acceptedAnswers: [
      "vote",
      "run for office",
      "join a political party",
      "help with a campaign",
      "join a civic group",
      "contact elected officials",
      "write to a newspaper",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-070",
    prompt: "What is one way Americans can serve their country?",
    acceptedAnswers: [
      "vote",
      "pay taxes",
      "obey the law",
      "serve in the military",
      "run for office",
      "work for local state or federal government",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-071",
    prompt: "Why is it important to pay federal taxes?",
    acceptedAnswers: [
      "required by law",
      "all people pay to fund the federal government",
      "required by the constitution",
      "civic duty",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  {
    id: "q-072",
    prompt: "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.",
    acceptedAnswers: [
      "required by law",
      "civic duty",
      "makes the draft fair if needed",
      "required by law civic duty",
    ],
    isDynamicOfficial: false,
    category: "Rights and Responsibilities",
    isSpecial65: false,
  },
  // American History: Colonial Period and Independence
  {
    id: "q-073",
    prompt: "The colonists came to America for many reasons. Name one.",
    acceptedAnswers: [
      "freedom",
      "political liberty",
      "religious freedom",
      "economic opportunity",
      "escape persecution",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-074",
    prompt: "Who lived in America before the Europeans arrived?",
    acceptedAnswers: ["american indians", "native americans", "indigenous peoples"],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: true,
  },
  {
    id: "q-075",
    prompt: "What group of people was taken and sold as slaves?",
    acceptedAnswers: ["africans", "people from africa"],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-076",
    prompt: "What war did the Americans fight to win independence from Britain?",
    acceptedAnswers: [
      "american revolution",
      "the american revolutionary war",
      "war for american independence",
      "revolutionary war",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-077",
    prompt: "Name one reason why the Americans declared independence from Britain.",
    acceptedAnswers: [
      "high taxes",
      "taxation without representation",
      "british soldiers stayed in americans houses",
      "they did not have self-government",
      "boston massacre",
      "boston tea party",
      "stamp act",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-078",
    prompt: "Who wrote the Declaration of Independence?",
    acceptedAnswers: ["thomas jefferson", "jefferson"],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: true,
  },
  {
    id: "q-079",
    prompt: "When was the Declaration of Independence adopted?",
    acceptedAnswers: ["july 4 1776", "july 4th 1776", "1776", "july 4"],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-080",
    prompt: "The American Revolution had many important events. Name one.",
    acceptedAnswers: [
      "battle of bunker hill",
      "declaration of independence",
      "washington crossing the delaware",
      "battle of saratoga",
      "valley forge",
      "battle of yorktown",
      "bunker hill",
      "saratoga",
      "yorktown",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-081",
    prompt: "There were 13 original states. Name five.",
    acceptedAnswers: [
      "new hampshire",
      "massachusetts",
      "rhode island",
      "connecticut",
      "new york",
      "new jersey",
      "pennsylvania",
      "delaware",
      "maryland",
      "virginia",
      "north carolina",
      "south carolina",
      "georgia",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-082",
    prompt: "What founding document was written in 1787?",
    acceptedAnswers: ["u.s. constitution", "the constitution", "constitution"],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-083",
    prompt: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
    acceptedAnswers: ["james madison", "alexander hamilton", "john jay", "publius", "madison", "hamilton", "jay"],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-084",
    prompt: "Why were the Federalist Papers important?",
    acceptedAnswers: [
      "they helped people understand the constitution",
      "they supported passing the constitution",
      "helped people understand the constitution",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-085",
    prompt: "Benjamin Franklin is famous for many things. Name one.",
    acceptedAnswers: [
      "founded the first free public libraries",
      "first postmaster general",
      "helped write the declaration of independence",
      "inventor",
      "u.s. diplomat",
      "diplomat",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-086",
    prompt: "George Washington is famous for many things. Name one.",
    acceptedAnswers: [
      "father of our country",
      "first president of the united states",
      "general of the continental army",
      "president of the constitutional convention",
      "first president",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: true,
  },
  {
    id: "q-087",
    prompt: "Thomas Jefferson is famous for many things. Name one.",
    acceptedAnswers: [
      "writer of the declaration of independence",
      "third president of the united states",
      "doubled the size of the united states",
      "louisiana purchase",
      "first secretary of state",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-088",
    prompt: "James Madison is famous for many things. Name one.",
    acceptedAnswers: [
      "father of the constitution",
      "fourth president of the united states",
      "president during the war of 1812",
      "one of the writers of the federalist papers",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  {
    id: "q-089",
    prompt: "Alexander Hamilton is famous for many things. Name one.",
    acceptedAnswers: [
      "first secretary of the treasury",
      "one of the writers of the federalist papers",
      "helped establish the first bank of the united states",
      "aide to general george washington",
    ],
    isDynamicOfficial: false,
    category: "Colonial Period and Independence",
    isSpecial65: false,
  },
  // B: 1800s
  {
    id: "q-090",
    prompt: "What territory did the United States buy from France in 1803?",
    acceptedAnswers: ["louisiana territory", "louisiana"],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-091",
    prompt: "Name one war fought by the United States in the 1800s.",
    acceptedAnswers: [
      "war of 1812",
      "mexican-american war",
      "civil war",
      "spanish-american war",
      "the civil war",
    ],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-092",
    prompt: "Name the U.S. war between the North and the South.",
    acceptedAnswers: ["the civil war", "civil war"],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-093",
    prompt: "The Civil War had many important events. Name one.",
    acceptedAnswers: [
      "battle of fort sumter",
      "emancipation proclamation",
      "battle of vicksburg",
      "battle of gettysburg",
      "shermans march",
      "surrender at appomattox",
      "lincoln was assassinated",
    ],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-094",
    prompt: "Abraham Lincoln is famous for many things. Name one.",
    acceptedAnswers: [
      "freed the slaves",
      "emancipation proclamation",
      "saved the union",
      "led the united states during the civil war",
      "16th president of the united states",
      "gettysburg address",
    ],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: true,
  },
  {
    id: "q-095",
    prompt: "What did the Emancipation Proclamation do?",
    acceptedAnswers: [
      "freed the slaves",
      "freed slaves in the confederacy",
      "freed slaves in the confederate states",
      "freed slaves in most southern states",
    ],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-096",
    prompt: "What U.S. war ended slavery?",
    acceptedAnswers: ["the civil war", "civil war"],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-097",
    prompt: "What amendment says all persons born or naturalized in the United States are U.S. citizens?",
    acceptedAnswers: ["14th amendment", "fourteenth amendment"],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-098",
    prompt: "When did all men get the right to vote?",
    acceptedAnswers: [
      "after the civil war",
      "during reconstruction",
      "with the 15th amendment",
      "1870",
      "15th amendment",
    ],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  {
    id: "q-099",
    prompt: "Name one leader of the women's rights movement in the 1800s.",
    acceptedAnswers: [
      "susan b. anthony",
      "elizabeth cady stanton",
      "sojourner truth",
      "harriet tubman",
      "lucretia mott",
      "lucy stone",
      "anthony",
    ],
    isDynamicOfficial: false,
    category: "1800s",
    isSpecial65: false,
  },
  // C: Recent American History
  {
    id: "q-100",
    prompt: "Name one war fought by the United States in the 1900s.",
    acceptedAnswers: [
      "world war i",
      "world war ii",
      "korean war",
      "vietnam war",
      "persian gulf war",
      "gulf war",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-101",
    prompt: "Why did the United States enter World War I?",
    acceptedAnswers: [
      "because germany attacked u.s. civilian ships",
      "to support the allied powers",
      "to oppose the central powers",
      "germany attacked us ships",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-102",
    prompt: "When did all women get the right to vote?",
    acceptedAnswers: ["1920", "after world war i", "with the 19th amendment", "19th amendment"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-103",
    prompt: "What was the Great Depression?",
    acceptedAnswers: [
      "longest economic recession in modern history",
      "a period of economic hardship",
      "economic depression",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-104",
    prompt: "When did the Great Depression start?",
    acceptedAnswers: ["the great crash 1929", "stock market crash of 1929", "1929"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-105",
    prompt: "Who was president during the Great Depression and World War II?",
    acceptedAnswers: ["franklin roosevelt", "roosevelt", "franklin d. roosevelt", "fdr"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-106",
    prompt: "Why did the United States enter World War II?",
    acceptedAnswers: [
      "bombing of pearl harbor",
      "japanese attacked pearl harbor",
      "to support the allied powers",
      "to oppose the axis powers",
      "pearl harbor",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-107",
    prompt: "Dwight Eisenhower is famous for many things. Name one.",
    acceptedAnswers: [
      "general during world war ii",
      "president at the end of the korean war",
      "34th president",
      "signed the federal-aid highway act",
      "created the interstate system",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-108",
    prompt: "Who was the United States' main rival during the Cold War?",
    acceptedAnswers: ["soviet union", "ussr", "russia"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-109",
    prompt: "During the Cold War, what was one main concern of the United States?",
    acceptedAnswers: ["communism", "nuclear war", "spread of communism"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-110",
    prompt: "Why did the United States enter the Korean War?",
    acceptedAnswers: ["to stop the spread of communism", "stop communism"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-111",
    prompt: "Why did the United States enter the Vietnam War?",
    acceptedAnswers: ["to stop the spread of communism", "stop communism"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-112",
    prompt: "What did the civil rights movement do?",
    acceptedAnswers: ["fought to end racial discrimination", "end racial discrimination", "end discrimination"],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-113",
    prompt: "Martin Luther King, Jr. is famous for many things. Name one.",
    acceptedAnswers: [
      "fought for civil rights",
      "worked for equality for all americans",
      "civil rights leader",
      "i have a dream speech",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: true,
  },
  {
    id: "q-114",
    prompt: "Why did the United States enter the Persian Gulf War?",
    acceptedAnswers: [
      "to force the iraqi military from kuwait",
      "to liberate kuwait",
      "free kuwait",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-115",
    prompt: "What major event happened on September 11, 2001 in the United States?",
    acceptedAnswers: [
      "terrorists attacked the united states",
      "terrorists attacked the world trade center",
      "9/11",
      "terrorist attack",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: true,
  },
  {
    id: "q-116",
    prompt: "Name one U.S. military conflict after the September 11, 2001 attacks.",
    acceptedAnswers: [
      "global war on terror",
      "war in afghanistan",
      "war in iraq",
      "afghanistan war",
      "iraq war",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-117",
    prompt: "Name one American Indian tribe in the United States.",
    acceptedAnswers: [
      "cherokee", "navajo", "sioux", "apache", "cheyenne", "lakota",
      "mohawk", "seminole", "chippewa", "crow", "blackfeet", "pueblо",
      "hopi", "oneida", "creek", "shawnee", "seneca", "iroquois",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  {
    id: "q-118",
    prompt: "Name one example of an American innovation.",
    acceptedAnswers: [
      "light bulb",
      "automobile",
      "skyscrapers",
      "airplane",
      "assembly line",
      "landing on the moon",
      "integrated circuit",
      "internet",
    ],
    isDynamicOfficial: false,
    category: "Recent American History",
    isSpecial65: false,
  },
  // Symbols and Holidays
  {
    id: "q-119",
    prompt: "What is the capital of the United States?",
    acceptedAnswers: ["washington d.c.", "washington dc", "washington", "d.c."],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
  {
    id: "q-120",
    prompt: "Where is the Statue of Liberty?",
    acceptedAnswers: [
      "new york harbor",
      "liberty island",
      "new jersey",
      "new york",
      "near new york city",
    ],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
  {
    id: "q-121",
    prompt: "Why does the flag have 13 stripes?",
    acceptedAnswers: [
      "because there were 13 original colonies",
      "represent the original colonies",
      "13 original colonies",
      "original colonies",
    ],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: true,
  },
  {
    id: "q-122",
    prompt: "Why does the flag have 50 stars?",
    acceptedAnswers: [
      "because there is one star for each state",
      "each star represents a state",
      "there are 50 states",
      "one star for each state",
    ],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
  {
    id: "q-123",
    prompt: "What is the name of the national anthem?",
    acceptedAnswers: ["the star-spangled banner", "star-spangled banner", "star spangled banner"],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
  {
    id: "q-124",
    prompt: 'The Nation\'s first motto was "E Pluribus Unum." What does that mean?',
    acceptedAnswers: ["out of many one", "we all become one", "out of many, one"],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
  {
    id: "q-125",
    prompt: "What is Independence Day?",
    acceptedAnswers: [
      "a holiday to celebrate u.s. independence from britain",
      "the country's birthday",
      "celebrate independence from britain",
    ],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
  {
    id: "q-126",
    prompt: "Name three national U.S. holidays.",
    acceptedAnswers: [
      "new year's day",
      "martin luther king jr day",
      "presidents day",
      "memorial day",
      "juneteenth",
      "independence day",
      "labor day",
      "columbus day",
      "veterans day",
      "thanksgiving day",
      "christmas day",
      "thanksgiving",
      "christmas",
    ],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: true,
  },
  {
    id: "q-127",
    prompt: "What is Memorial Day?",
    acceptedAnswers: [
      "a holiday to honor soldiers who died in military service",
      "honor soldiers who died",
      "honor fallen soldiers",
    ],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
  {
    id: "q-128",
    prompt: "What is Veterans Day?",
    acceptedAnswers: [
      "a holiday to honor people in the u.s. military",
      "a holiday to honor people who have served in the u.s. military",
      "honor veterans",
      "honor military service",
    ],
    isDynamicOfficial: false,
    category: "Symbols and Holidays",
    isSpecial65: false,
  },
];

export function getQuestionCountTarget(): number {
  return QUESTION_BANK.length;
}

export function getQuestionsByCategory(): Record<string, CivicsQuestion[]> {
  const map: Record<string, CivicsQuestion[]> = {};
  for (const q of QUESTION_BANK) {
    const cat = q.category ?? "General";
    if (!map[cat]) map[cat] = [];
    map[cat].push(q);
  }
  return map;
}

export function getSpecial65Questions(): CivicsQuestion[] {
  return QUESTION_BANK.filter((q) => q.isSpecial65);
}
